apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic-app.fullname" . }}
  labels:
    {{- include "basic-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "basic-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "basic-app.selectorLabels" . | nindent 8 }}
        {{- include "basic-app.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "basic-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.podEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          {{- with .Values.probes }}
          livenessProbe:
            httpGet:
              path: {{ .liveness.path }}
              port: {{ .liveness.port }}
            initialDelaySeconds: {{ .liveness.initialDelaySeconds }}
            periodSeconds: {{ .liveness.periodSeconds }}
            timeoutSeconds: {{ .liveness.timeoutSeconds }}
            successThreshold: {{ .liveness.successThreshold }}
            failureThreshold: {{ .liveness.failureThreshold }}
          {{- end }}
          {{- with .Values.probes }}
          readinessProbe:
            httpGet:
              path: {{ .readiness.path }}
              port: {{ .readiness.port }}
            initialDelaySeconds: {{ .readiness.initialDelaySeconds }}
            periodSeconds: {{ .readiness.periodSeconds }}
            timeoutSeconds: {{ .readiness.timeoutSeconds }}
            successThreshold: {{ .readiness.successThreshold }}
            failureThreshold: {{ .readiness.failureThreshold }}
          {{- end }}
          resources: {}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
